name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: parking
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # You can adjust the PHP version

      - name: Composer Update
        run: composer update
      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Set up environment
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate
      - name: Debug DNS Resolution
        run: |
          ping mysql
          nslookup mysql
      - name: Display MySQL logs
        run: cat /var/log/mysql/error.log

      - name: Run database migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: parking
          DB_USERNAME: root
          DB_PASSWORD: password
        run: php artisan migrate:fresh --force
