name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup-laravel:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mysql, mongodb

      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Configure Laravel
        run: |
           cp .env.ci .env
           php artisan key:generate
           php artisan config:clear
      - name: Upload setup artifact
        uses: actions/upload-artifact@v2
        with:
          name: setup-artifact
          path: ${{ github.workspace }}
          if-no-files-found: error
  migrate:
    runs-on: ubuntu-latest
    services:
      mysql-service:
        image: mysql:8
        env:
          MYSQL_DATABASE: parking
          MYSQL_USER: admin
          MYSQL_ROOT_PASSWORD: password
          MYSQL_PASSWORD: password
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
            mongodb-version: '4.4.9'
            mongodb-port: 27017
            mongodb-username: root
            mongodb-password: password
            mongodb-db: parking

      - name: Run migrations
        run: php artisan migrate
        with:
          name: setup-artifact
        env:
          DB_PORT: ${{ job.services.mysql-service.ports[3306]}}
          DB_HOST: 127.0.0.1
